CREATE TABLE songs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  song_file VARCHAR(255) NOT NULL,
  lyrics_file VARCHAR(255) DEFAULT NULL,
  video_file VARCHAR(255) DEFAULT NULL,
  artwork_file VARCHAR(255) DEFAULT NULL,
  mood VARCHAR(255) DEFAULT 'The Delta Blues of Growing Older',
  play_count INT DEFAULT 0,
  published TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);